In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [66]:
df=pd.read_csv('./Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [67]:
data=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [68]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [69]:
label_encoder_gender=LabelEncoder()

data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [70]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [71]:
# One hot encoder Geography

one_hot_enc_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=one_hot_enc_geo.fit_transform(data[['Geography']]).toarray()
_df=pd.DataFrame(geo_encoded,columns=one_hot_enc_geo.get_feature_names_out(['Geography']))

_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [72]:
data=pd.concat([data.drop('Geography',axis=1),_df],axis=1)

In [73]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [74]:
# split the data
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [75]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
# scale
scalar=StandardScaler()

X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [76]:
# Save the pickle files
# this files for salary regression
with open('label_encoder_gender_sal.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('one_ht_enc_geo_sal.pkl','wb') as file:
    pickle.dump(one_hot_enc_geo,file)
with open('scalar_sal.pkl','wb') as file:
    pickle.dump(scalar,file)

##ANN Regression Problem Statment

In [77]:
# ANN Regression 
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [78]:
# Build our Model
model=Sequential([
    Dense(64,activation='relu',input_shape=((X_train.shape[1], ))), #HL1 first hidden layer connected with input layer
    Dense(32,activation='relu'), #HL2 
    Dense(1,activation='sigmoid') #output3 
])

C:\Users\ddurande\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [79]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [91]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate=0.0001)

In [92]:
# COmpile the model
model.compile(optimizer=optimizer,loss='mean_absolute_error',metrics=['mae'])

In [93]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [94]:
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir="regressionlogs/fit1"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callbacks]  #,early_stopping_callbacks
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99989.2656 - mae: 99989.2656 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100890.6016 - mae: 100890.6016 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100797.4531 - mae: 100797.4531 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100060.1875 - mae: 100060.1875 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100817.3047 - mae: 100817.3047 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99656.0703 - mae: 99656.0703 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100368.6172 - mae: 100368.6172 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100947.6172 - mae: 100947.6172 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101576.8594 - mae: 101576.8594 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101396.8906 - mae: 101396.8906 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101445.8438 - mae: 101445.8438 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101095.6797 - mae: 101095.6797 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100316.2812 - mae: 100316.2812 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100728.2031 - mae: 100728.2031 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101541.0703 - mae: 101541.0703 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100516.4688 - mae: 100516.4688 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100090.1953 - mae: 100090.1953 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101036.1953 - mae: 101036.1953 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100389.1875 - mae: 100389.1875 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99861.5625 - mae: 99861.5625 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100670.8281 - mae: 100670.8281 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 102519.4844 - mae: 102519.4844 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100629.3828 - mae: 100629.3828 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100449.3828 - mae: 100449.3828 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101461.7578 - mae: 101461.7578 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99344.1953 - mae: 99344.1953 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101566.1484 - mae: 101566.1484 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101054.3672 - mae: 101054.3672 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100227.0938 - mae: 100227.0938 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100605.2344 - mae: 100605.2344 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99403.9922 - mae: 99403.9922 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100982.6562 - mae: 100982.6562 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100137.2656 - mae: 100137.2656 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100748.1328 - mae: 100748.1328 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100672.8125 - mae: 100672.8125 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100115.1641 - mae: 100115.1641 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101750.2500 - mae: 101750.2500 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100023.4844 - mae: 100023.4844 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99755.6484 - mae: 99755.6484 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100256.3281 - mae: 100256.3281 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100309.8047 - mae: 100309.8047 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101329.6797 - mae: 101329.6797 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100476.4062 - mae: 100476.4062 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101406.1719 - mae: 101406.1719 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99831.2891 - mae: 99831.2891 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99662.8594 - mae: 99662.8594 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99610.8594 - mae: 99610.8594 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99737.7031 - mae: 99737.7031 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99998.9688 - mae: 99998.9688 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100768.5312 - mae: 100768.5312 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100514.7891 - mae: 100514.7891 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100579.9453 - mae: 100579.9453 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99844.2031 - mae: 99844.2031 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100609.9453 - mae: 100609.9453 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100686.0078 - mae: 100686.0078 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100708.7812 - mae: 100708.7812 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100931.9219 - mae: 100931.9219 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101080.9453 - mae: 101080.9453 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100382.6484 - mae: 100382.6484 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100034.5703 - mae: 100034.5703 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99417.9844 - mae: 99417.9844 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100449.6797 - mae: 100449.6797 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100079.4766 - mae: 100079.4766 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100672.6641 - mae: 100672.6641 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101138.1016 - mae: 101138.1016 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100929.6719 - mae: 100929.6719 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99591.9141 - mae: 99591.9141 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100646.0234 - mae: 100646.0234 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101094.7656 - mae: 101094.7656 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101007.7969 - mae: 101007.7969 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99992.9141 - mae: 99992.9141 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100792.2500 - mae: 100792.2500 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101099.2422 - mae: 101099.2422 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101465.2734 - mae: 101465.2734 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100073.3750 - mae: 100073.3750 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100726.8750 - mae: 100726.8750 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100239.5156 - mae: 100239.5156 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101098.0781 - mae: 101098.0781 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100297.8125 - mae: 100297.8125 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99917.6328 - mae: 99917.6328 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99912.0234 - mae: 99912.0234 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100984.3906 - mae: 100984.3906 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100588.4688 - mae: 100588.4688 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100993.0469 - mae: 100993.0469 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100399.6641 - mae: 100399.6641 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99136.0625 - mae: 99136.0625 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100639.4766 - mae: 100639.4766 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100783.5625 - mae: 100783.5625 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99499.9688 - mae: 99499.9688 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100184.5078 - mae: 100184.5078 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100551.0312 - mae: 100551.0312 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101429.6172 - mae: 101429.6172 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101694.0938 - mae: 101694.0938 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101292.7266 - mae: 101292.7266 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100485.6953 - mae: 100485.6953 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99888.3672 - mae: 99888.3672 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 101099.6875 - mae: 101099.6875 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100031.1562 - mae: 100031.1562 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99056.9766 - mae: 99056.9766 - val_loss: 98725.0625 - val_mae: 98725.0625
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100528.4766 - mae: 100528.4766 - val_loss: 98725.0625 - val_mae: 98725.0625

In [84]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [88]:
%tensorboard  --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 17160), started 0:00:25 ago. (Use '!kill 17160' to kill it.)

In [89]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test MAE{test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 100870.6641 - mae: 100870.6641
Test MAE98725.0625

In [97]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.